### ISSUE TITLE
List of available tools

### ISSUE THREAD

**Issue by kyyberi** [APIOps/APIOps-cycles#18]
I know APIOps Cycles is tool agnostic methodology. Yet some of the products are mentioned indirectly in some sections. 

Should we have a separate resource file where we list tools for various steps in the methodology. Vendors and community could push their suggestions in that file. 

Having some practical tools to look at might take the methodology towards more practical direction. 
In my opinion we should somehow separate open source tools from closed source in the list. We could refer to sections in the list from various location in the methodology. This might also raise the interest of vendors to participate. 

I'll make a suggestion about the structure in this issue later.

**Comment by kyyberi** [comment]
Ping @mniinio

**Comment by kyyberi** [comment]
## API management platforms

### Open source

### Saas

### Other


## Gateways

### Open source

### Saas

### Other


## Proxies

### Open source

### Saas

### Other


## API Testing

### Open source

### Saas

### Other


## API Monitoring

### Open source

### Saas

### Other



## API design and description

### Open source

### Saas

### Other


## Business templates

### Open source

### Saas

### Other

**Comment by mniinio** [comment]
This is obviously at the core of what we consult and do in Digia and what other companies in the field are doing, too. I think this should be something the vendors and users could contribute to. Listing something as open source or closed source is also a bit tricky as most of the open source products are also sold as "commercial products" partly or totally closed sourced. Commercial products also include more and more open source components. 

So I would maybe prefer we either
- don't get involved in the tooling at all in this documentation
- maybe as an exception if there is a specific reason for doing so (like the fact that the versioning strategies are different) and these differences could be listed of course in another page but mostly they will live in the tool providers sites anyway

**Comment by kyyberi** [comment]
Well, open source is for what you can download the code which is licensed under OSI licenses. That is not so tricky and we just define it that way.

**Comment by kyyberi** [comment]
"I think this should be something the vendors and users could contribute to" Yes, this is what I expect to see. I never thought that we (you, me and a few others) build the list

**Comment by kyyberi** [comment]
Wont fix, closing
