### ISSUE TITLE
Move sources under APIOps org 

### ISSUE THREAD

**Issue by kyyberi** [APIOps/APIOps-cycles#3]
APIOps cycles source files should be moved under this repository. Otherwise we can't take the process of further development.

**Comment by kyyberi** [comment]
Here's reminder how:
https://gist.github.com/msrose/2feacb303035d11d2d05

**Comment by kyyberi** [comment]
Shall I do it?

**Comment by kyyberi** [comment]
Since this is referenced more and more publicly, we just have to have material in proper repository. I'll do the move today.

**Comment by kyyberi** [comment]
Content has been moved. Could you @mniinio remove the domain address from your repository?

**Comment by mniinio** [comment]
Thanks for moving the site @kyyberi . Have now removed all referensces and public site
